# -*- coding: utf-8 -*-
"""
Created on Wed Apr  2 16:27:10 2014

This is a helper module with some functions to fastly use the data generated
by PAM in Nest

@author: martin
"""
import nest

def Connect(g1, g2, connections, delays, weights, delay_factor):
    """ Connects group g1 of neurons with group g2 of neurons using the
    connection- and delay-matrix generated by PAM
    
    g1,
    g2              : Groups of neurons
    
    connnections    : Connection matrix generated in PAM
    
    delays          : Delay matrix generated in PAM
    
    weights         : A standard weight for the connection
    
    delay_factor    : A factor for the delay
    
    
    Example:
        
        Connect(g1, g2, m['c'][0], m['d'][0], 2.0, DELAY_FACTOR)
    """
    for i in range(0, len(connections)):
        for j in range(0, len(connections[0])):
            # if a synapse has really been created
            if connections[i][j] > 0:
                nest.Connect([g1[i]], [g2[int(connections[i][j])]], params={'weight': 2.0, 'delay': delays[i][j] * delay_factor})
